"""phase 4.2 models

Revision ID: 0460b5324045
Revises: 7ca27c1c61b3
Create Date: 2026-09-12 14:11:29.192150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0460b5324045'
down_revision: Union[str, Sequence[str], None] = '7ca27c1c61b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagery_processing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imagery_id', sa.UUID(), nullable=False),
    sa.Column('processing_version', sa.String(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('processed_storage_reference', sa.String(), nullable=True),
    sa.Column('original_sha256_hash', sa.String(), nullable=False),
    sa.Column('processed_sha256_hash', sa.String(), nullable=True),
    sa.Column('original_width_px', sa.Float(), nullable=True),
    sa.Column('original_height_px', sa.Float(), nullable=True),
    sa.Column('processed_width_px', sa.Float(), nullable=True),
    sa.Column('processed_height_px', sa.Float(), nullable=True),
    sa.Column('color_space', sa.String(), nullable=True),
    sa.Column('orientation_corrected', sa.Boolean(), nullable=False),
    sa.Column('resize_applied', sa.Boolean(), nullable=False),
    sa.Column('quality_classification', sa.Enum('GOOD', 'REVIEW', 'UNSUITABLE', name='qualityclassification'), nullable=True),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('preprocessing_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['imagery_id'], ['imagery_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagery_processing')
    # ### end Alembic commands ###
