"""Add AnomalyExplanation model

Revision ID: 092cf2c2b9fd
Revises: 44badfc31cb2
Create Date: 2026-09-12 11:26:04.848952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092cf2c2b9fd'
down_revision: Union[str, Sequence[str], None] = '44badfc31cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_explanation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anomaly_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('primary_factor', sa.String(), nullable=True),
    sa.Column('contributing_factors_json', sa.JSON(), nullable=False),
    sa.Column('supporting_evidence_json', sa.JSON(), nullable=False),
    sa.Column('contradicting_evidence_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_strength', sa.Enum('INSUFFICIENT', 'WEAK', 'MODERATE', 'STRONG', name='evidencestrength'), nullable=False),
    sa.Column('analysis_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('explanation_version', sa.String(), nullable=False),
    sa.Column('data_quality_notes', sa.JSON(), nullable=False),
    sa.Column('uncertainty_notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomaly.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_run.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anomaly_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_explanation')
    # ### end Alembic commands ###
