"""phase_4_3_models

Revision ID: 0c5e355aaa35
Revises: 83b2590c0bf9
Create Date: 2026-09-12 14:39:37.481178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5e355aaa35'
down_revision: Union[str, Sequence[str], None] = '83b2590c0bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagery_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imagery_id', sa.UUID(), nullable=False),
    sa.Column('processing_id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.dialects.postgresql.ENUM('SIMULATED', 'DRONE', 'SATELLITE', name='imagerysourcetype', create_type=False), nullable=False),
    sa.Column('analysis_version', sa.String(), nullable=False),
    sa.Column('roi_method', sa.String(), nullable=False),
    sa.Column('mean_red', sa.Float(), nullable=True),
    sa.Column('mean_green', sa.Float(), nullable=True),
    sa.Column('mean_blue', sa.Float(), nullable=True),
    sa.Column('green_dominance', sa.Float(), nullable=True),
    sa.Column('green_pixel_fraction', sa.Float(), nullable=True),
    sa.Column('valid_pixel_fraction', sa.Float(), nullable=True),
    sa.Column('spatial_mean', sa.Float(), nullable=True),
    sa.Column('spatial_std', sa.Float(), nullable=True),
    sa.Column('grid_data', sa.JSON(), nullable=True),
    sa.Column('analysis_status', sa.Enum('READY', 'REVIEW', 'BLOCKED', 'INSUFFICIENT_EVIDENCE', name='analysisstatus'), nullable=False),
    sa.Column('baseline_analysis_id', sa.UUID(), nullable=True),
    sa.Column('absolute_change', sa.Float(), nullable=True),
    sa.Column('relative_change', sa.Float(), nullable=True),
    sa.Column('change_classification', sa.Enum('INCREASE', 'DECREASE', 'STABLE', 'INSUFFICIENT_EVIDENCE', name='temporalchangeclassification'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['baseline_analysis_id'], ['imagery_analysis.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['imagery_id'], ['imagery_record.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.ForeignKeyConstraint(['processing_id'], ['imagery_processing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagery_analysis')
    # ### end Alembic commands ###
