"""Add Anomaly model

Revision ID: 42badfc31cb0
Revises: e486b2244f74
Create Date: 2026-09-12 10:19:32.436319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42badfc31cb0'
down_revision: Union[str, Sequence[str], None] = 'e486b2244f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=True),
    sa.Column('sensor_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anomaly_type', sa.Enum('OUT_OF_RANGE', 'SUDDEN_SPIKE', 'SUDDEN_DROP', 'RATE_OF_CHANGE', 'STALE_VALUE', 'SENSOR_DROPOUT', 'ENVIRONMENTAL', name='anomalytype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='anomalyseverity'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source_provenance', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='anomalystatus'), nullable=False),
    sa.Column('limiting_factor', sa.String(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly')
    # ### end Alembic commands ###
