"""Add ReviewState and ReviewAction

Revision ID: 593b45ca8657
Revises: cfcdab8989a7
Create Date: 2026-09-12 15:36:42.963342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593b45ca8657'
down_revision: Union[str, Sequence[str], None] = 'cfcdab8989a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    review_state_enum = ENUM('NOT_STARTED', 'IN_REVIEW', 'NEEDS_ATTENTION', 'READY_FOR_EXTERNAL_REVIEW', 'CLOSED', name='reviewstate', create_type=False)
    review_action_type_enum = ENUM('START_REVIEW', 'FLAG_FOR_ATTENTION', 'MARK_REVIEWED', 'REQUEST_MORE_EVIDENCE', 'CLOSE_REVIEW', name='reviewactiontype', create_type=False)
    
    review_state_enum.create(op.get_bind())
    review_action_type_enum.create(op.get_bind())
    
    op.add_column('evidence_package', sa.Column('review_state', review_state_enum, nullable=False, server_default='NOT_STARTED'))
    
    op.create_table(
        'review_action',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('package_id', sa.UUID(), nullable=False),
        sa.Column('actor', sa.String(), nullable=False),
        sa.Column('action', review_action_type_enum, nullable=False),
        sa.Column('note', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['package_id'], ['evidence_package.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_action')
    op.drop_column('evidence_package', 'review_state')
    
    sa.Enum(name='reviewstate').drop(op.get_bind())
    sa.Enum(name='reviewactiontype').drop(op.get_bind())
    # ### end Alembic commands ###
