"""remove_unique_hash

Revision ID: 7ca27c1c61b3
Revises: bb5a54dea966
Create Date: 2026-09-12 14:01:21.451640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ca27c1c61b3'
down_revision: Union[str, Sequence[str], None] = 'bb5a54dea966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imagery_record', 'processing_status',
               existing_type=postgresql.ENUM('INGESTED', 'REJECTED', name='imageryprocessingstatus'),
               nullable=True)
    op.drop_constraint(op.f('imagery_record_sha256_hash_key'), 'imagery_record', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('imagery_record_sha256_hash_key'), 'imagery_record', ['sha256_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('imagery_record', 'processing_status',
               existing_type=postgresql.ENUM('INGESTED', 'REJECTED', name='imageryprocessingstatus'),
               nullable=False)
    # ### end Alembic commands ###
