"""phase_4_4_cross_validation

Revision ID: 986affc55675
Revises: 0c5e355aaa35
Create Date: 2026-09-12 15:00:16.828562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986affc55675'
down_revision: Union[str, Sequence[str], None] = '0c5e355aaa35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_validation_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('imagery_analysis_id', sa.UUID(), nullable=True),
    sa.Column('comparison_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comparison_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_trend', sa.dialects.postgresql.ENUM('INCREASE', 'DECREASE', 'STABLE', 'INSUFFICIENT_EVIDENCE', name='temporalchangeclassification', create_type=False), nullable=True),
    sa.Column('imagery_trend', sa.dialects.postgresql.ENUM('INCREASE', 'DECREASE', 'STABLE', 'INSUFFICIENT_EVIDENCE', name='temporalchangeclassification', create_type=False), nullable=True),
    sa.Column('model_change', sa.Float(), nullable=True),
    sa.Column('imagery_change', sa.Float(), nullable=True),
    sa.Column('temporal_alignment_status', sa.Enum('GOOD', 'REVIEW', 'INSUFFICIENT_EVIDENCE', name='temporalalignmentstatus'), nullable=False),
    sa.Column('result_status', sa.Enum('CONSISTENT', 'PARTIALLY_CONSISTENT', 'INCONSISTENT', 'INSUFFICIENT_EVIDENCE', name='validationresultstatus'), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='validationconfidence'), nullable=False),
    sa.Column('evidence_summary', sa.String(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['imagery_analysis_id'], ['imagery_analysis.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_run.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cross_validation_run')
    # ### end Alembic commands ###
