"""Add ImageryRecord

Revision ID: baf22839caf6
Revises: 092cf2c2b9fd
Create Date: 2026-09-12 13:35:22.355621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf22839caf6'
down_revision: Union[str, Sequence[str], None] = '092cf2c2b9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagery_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('SIMULATED', 'DRONE', 'SATELLITE', name='imagerysourcetype'), nullable=False),
    sa.Column('capture_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Float(), nullable=False),
    sa.Column('storage_reference', sa.String(), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=False),
    sa.Column('width_px', sa.Float(), nullable=True),
    sa.Column('height_px', sa.Float(), nullable=True),
    sa.Column('resolution_meters', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.Enum('INGESTED', 'REJECTED', name='imageryprocessingstatus'), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256_hash')
    )
    op.alter_column('anomaly_explanation', 'data_quality_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               postgresql_using='data_quality_notes::json',
               nullable=False)
    op.alter_column('anomaly_explanation', 'uncertainty_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               postgresql_using='uncertainty_notes::json',
               nullable=False)
    op.drop_index(op.f('ix_anomaly_explanation_anomaly_id'), table_name='anomaly_explanation')
    op.create_unique_constraint('uq_anomaly_explanation_anomaly_id', 'anomaly_explanation', ['anomaly_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_anomaly_explanation_anomaly_id', 'anomaly_explanation', type_='unique')
    op.create_index(op.f('ix_anomaly_explanation_anomaly_id'), 'anomaly_explanation', ['anomaly_id'], unique=False)
    op.alter_column('anomaly_explanation', 'uncertainty_notes',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anomaly_explanation', 'data_quality_notes',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_table('imagery_record')
    # ### end Alembic commands ###
