"""Add EvidencePackage model

Revision ID: cfcdab8989a7
Revises: 986affc55675
Create Date: 2026-09-12 15:22:42.027175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcdab8989a7'
down_revision: Union[str, Sequence[str], None] = '986affc55675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_package',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reporting_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY_FOR_REVIEW', 'INCOMPLETE', name='packagestatus'), nullable=False),
    sa.Column('completeness', sa.Enum('COMPLETE', 'PARTIAL', 'INSUFFICIENT_EVIDENCE', name='completenessclassification'), nullable=False),
    sa.Column('sensor_evidence_json', sa.JSON(), nullable=False),
    sa.Column('model_evidence_json', sa.JSON(), nullable=False),
    sa.Column('carbon_evidence_json', sa.JSON(), nullable=False),
    sa.Column('anomaly_evidence_json', sa.JSON(), nullable=False),
    sa.Column('imagery_evidence_json', sa.JSON(), nullable=False),
    sa.Column('cross_validation_evidence_json', sa.JSON(), nullable=False),
    sa.Column('limitations_json', sa.JSON(), nullable=False),
    sa.Column('canonical_hash', sa.String(), nullable=True),
    sa.Column('contains_simulated_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_package')
    # ### end Alembic commands ###
