
"""Phase 2 models

Revision ID: e486b2244f74
Revises: e577091bd11f
Create Date: 2026-09-12 09:59:52.554685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e486b2244f74'
down_revision: Union[str, Sequence[str], None] = 'e577091bd11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('nitrogen', sa.Float(), nullable=True),
    sa.Column('dissolved_oxygen', sa.Float(), nullable=True),
    sa.Column('light', sa.Float(), nullable=True),
    sa.Column('turbidity', sa.Float(), nullable=True),
    sa.Column('water_level', sa.Float(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='modelrunstatus'), nullable=True),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biomass_estimate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('biomass_g_per_l', sa.Float(), nullable=False),
    sa.Column('light_factor', sa.Float(), nullable=False),
    sa.Column('temp_factor', sa.Float(), nullable=False),
    sa.Column('ph_factor', sa.Float(), nullable=False),
    sa.Column('n_factor', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_run.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_estimate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_co2_kg', sa.Float(), nullable=False),
    sa.Column('retained_co2_kg', sa.Float(), nullable=True),
    sa.Column('operational_emissions_kg', sa.Float(), nullable=True),
    sa.Column('net_carbon_removed_kg', sa.Float(), nullable=True),
    sa.Column('realized_c_fraction', sa.Float(), nullable=False),
    sa.Column('end_use', sa.String(), nullable=False),
    sa.Column('permanence_horizon_label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_run.id'], ),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carbon_estimate')
    op.drop_table('biomass_estimate')
    op.drop_table('model_run')
    op.drop_table('environmental_snapshot')
    # ### end Alembic commands ###
