"""Initial migration

Revision ID: e577091bd11f
Revises: 
Create Date: 2026-09-12 08:03:19.366228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e577091bd11f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pond',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('volume_liters', sa.Float(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'harvested', 'offline', name='pondstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('temperature', 'ph', 'dissolved_oxygen', 'turbidity', 'light', 'conductivity', 'water_level', 'nitrogen', 'biomass', name='sensortype'), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('calibration_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['pond.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_reading',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality_flag', sa.Enum('ok', 'outlier', 'missing', 'interpolated', name='qualityflag'), nullable=False),
    sa.Column('source_type', sa.Enum('measured', 'simulated', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_reading')
    op.drop_table('sensor')
    op.drop_table('pond')
    op.drop_table('farm')
    # ### end Alembic commands ###
