export interface Pond {
  id: string;
  name: string;
  farmId: string;
  farmName: string;
  species: string;
  speciesCommon: string;
  status: 'Healthy' | 'Attention' | 'Critical' | 'Offline';
  biomass: number;
  temperature: number;
  ph: number;
  dissolvedOxygen: number;
  turbidity: number;
  nitrogen: number;
  volumeLiters: number;
  areaSqM: number;
  depthCm: number;
  pondType: string;
  description: string;
  lastHarvest?: string;
  dailyGrowthRate: number;
  co2InjectionRate: number;
  imageUrl: string;
}

export const DEMO_PONDS: Pond[] = [
  // 1. Kutch Bio-Raceway Facility (4 Ponds)
  {
    id: 'p-1',
    name: 'Pond Narmada',
    farmId: 'farm-1',
    farmName: 'Kutch Bio-Raceway Facility',
    species: 'Chlorella vulgaris',
    speciesCommon: 'Green Microalgae',
    status: 'Healthy',
    biomass: 0.86,
    temperature: 28.4,
    ph: 8.2,
    dissolvedOxygen: 7.4,
    turbidity: 34,
    nitrogen: 8.8,
    volumeLiters: 120000,
    areaSqM: 3200,
    depthCm: 25,
    pondType: 'Open Raceway',
    description: 'Flagship high-yield raceway pond with paddle wheel circulation. Optimized for Chlorella vulgaris biomass production under Gujarat solar irradiance.',
    lastHarvest: '2026-09-10',
    dailyGrowthRate: 13.2,
    co2InjectionRate: 0.9,
    imageUrl: '/images/ponds/pond_narmada.jpg',
  },
  {
    id: 'p-2',
    name: 'Pond Sabarmati',
    farmId: 'farm-1',
    farmName: 'Kutch Bio-Raceway Facility',
    species: 'Spirulina platensis',
    speciesCommon: 'Blue-Green Spirulina',
    status: 'Attention',
    biomass: 0.82,
    temperature: 28.8,
    ph: 8.5,
    dissolvedOxygen: 6.1,
    turbidity: 39,
    nitrogen: 4.3,
    volumeLiters: 95000,
    areaSqM: 2600,
    depthCm: 22,
    pondType: 'Open Raceway',
    description: 'High-alkalinity raceway dedicated to Spirulina cultivation. Supplemental nitrogen dosing active.',
    lastHarvest: '2026-09-06',
    dailyGrowthRate: 10.4,
    co2InjectionRate: 0.7,
    imageUrl: '/images/ponds/pond_sabarmati.jpg',
  },
  {
    id: 'p-kutch-3',
    name: 'Pond Tapi',
    farmId: 'farm-1',
    farmName: 'Kutch Bio-Raceway Facility',
    species: 'Scenedesmus obliquus',
    speciesCommon: 'Green Scenedesmus',
    status: 'Healthy',
    biomass: 0.88,
    temperature: 28.1,
    ph: 8.0,
    dissolvedOxygen: 7.8,
    turbidity: 35,
    nitrogen: 8.6,
    volumeLiters: 110000,
    areaSqM: 2900,
    depthCm: 25,
    pondType: 'Open Raceway',
    description: 'Enclosed photobioreactor system for high-purity Scenedesmus cultivation with direct flue-gas CO₂ injection.',
    lastHarvest: '2026-09-11',
    dailyGrowthRate: 12.0,
    co2InjectionRate: 1.2,
    imageUrl: '/images/ponds/pond_tapi.jpg',
  },
  {
    id: 'p-kutch-4',
    name: 'Pond Mahi',
    farmId: 'farm-1',
    farmName: 'Kutch Bio-Raceway Facility',
    species: 'Dunaliella salina',
    speciesCommon: 'Beta-Carotene Halotolerant Algae',
    status: 'Healthy',
    biomass: 0.79,
    temperature: 29.2,
    ph: 8.3,
    dissolvedOxygen: 7.1,
    turbidity: 31,
    nitrogen: 7.9,
    volumeLiters: 85000,
    areaSqM: 2200,
    depthCm: 20,
    pondType: 'High-Salinity Raceway',
    description: 'High-salinity pond utilizing natural brine concentrations for robust beta-carotene accumulation.',
    lastHarvest: '2026-08-30',
    dailyGrowthRate: 11.5,
    co2InjectionRate: 0.85,
    imageUrl: '/images/ponds/pond_mahi.jpg',
  },

  // 2. Rameswaram Coastal Algae Hub (3 Ponds)
  {
    id: 'p-5',
    name: 'Pond Kaveri',
    farmId: 'farm-2',
    farmName: 'Rameswaram Coastal Algae Hub',
    species: 'Chlorella vulgaris',
    speciesCommon: 'High-Yield Lipid Strain',
    status: 'Healthy',
    biomass: 0.91,
    temperature: 27.8,
    ph: 8.1,
    dissolvedOxygen: 7.6,
    turbidity: 36,
    nitrogen: 8.9,
    volumeLiters: 150000,
    areaSqM: 3800,
    depthCm: 28,
    pondType: 'Precision Raceway',
    description: 'High-throughput raceway cultivation basin with integrated hydraulic recirculators and micro-bubble carbonation injectors.',
    lastHarvest: '2026-09-09',
    dailyGrowthRate: 14.1,
    co2InjectionRate: 1.1,
    imageUrl: '/images/ponds/pond_kaveri.jpg',
  },
  {
    id: 'p-ram-2',
    name: 'Pond Vaigai',
    farmId: 'farm-2',
    farmName: 'Rameswaram Coastal Algae Hub',
    species: 'Spirulina platensis',
    speciesCommon: 'Tropical Coastal Strain',
    status: 'Healthy',
    biomass: 0.84,
    temperature: 27.5,
    ph: 8.3,
    dissolvedOxygen: 7.2,
    turbidity: 33,
    nitrogen: 8.4,
    volumeLiters: 100000,
    areaSqM: 2700,
    depthCm: 24,
    pondType: 'Open Raceway',
    description: 'Coastal nutrient-circulated basin engineered for robust blue-green algae extraction.',
    lastHarvest: '2026-09-04',
    dailyGrowthRate: 11.8,
    co2InjectionRate: 0.95,
    imageUrl: '/images/ponds/pond_vaigai.jpg',
  },
  {
    id: 'p-ram-3',
    name: 'Pond Tamirabarani',
    farmId: 'farm-2',
    farmName: 'Rameswaram Coastal Algae Hub',
    species: 'Haematococcus pluvialis',
    speciesCommon: 'Astaxanthin Rich Strain',
    status: 'Healthy',
    biomass: 0.95,
    temperature: 27.1,
    ph: 7.9,
    dissolvedOxygen: 7.9,
    turbidity: 29,
    nitrogen: 9.0,
    volumeLiters: 90000,
    areaSqM: 2400,
    depthCm: 22,
    pondType: 'Closed PBR Array',
    description: 'Specialized closed photobioreactor array for red ketocarotenoid synthesis.',
    lastHarvest: '2026-09-08',
    dailyGrowthRate: 12.4,
    co2InjectionRate: 1.15,
    imageUrl: '/images/ponds/pond_tamirabarani.jpg',
  },

  // 3. Sambhar Salt Lake Bio-Culture Site (3 Ponds)
  {
    id: 'p-4',
    name: 'Pond Luni',
    farmId: 'farm-3',
    farmName: 'Sambhar Salt Lake Bio-Culture Site',
    species: 'Dunaliella salina',
    speciesCommon: 'Hypersaline Beta-Carotene Algae',
    status: 'Healthy',
    biomass: 0.81,
    temperature: 29.4,
    ph: 8.4,
    dissolvedOxygen: 6.9,
    turbidity: 30,
    nitrogen: 7.8,
    volumeLiters: 180000,
    areaSqM: 4500,
    depthCm: 25,
    pondType: 'High-Salinity Raceway',
    description: 'Natural inland salt playa cultivation capturing extreme Rajasthan solar irradiance.',
    lastHarvest: '2026-09-01',
    dailyGrowthRate: 11.2,
    co2InjectionRate: 0.85,
    imageUrl: '/images/ponds/pond_luni.jpg',
  },
  {
    id: 'p-sam-2',
    name: 'Pond Pushkar',
    farmId: 'farm-3',
    farmName: 'Sambhar Salt Lake Bio-Culture Site',
    species: 'Spirulina platensis',
    speciesCommon: 'High-Alkaline Biomass Strain',
    status: 'Healthy',
    biomass: 0.87,
    temperature: 28.9,
    ph: 8.6,
    dissolvedOxygen: 7.3,
    turbidity: 37,
    nitrogen: 8.5,
    volumeLiters: 120000,
    areaSqM: 3100,
    depthCm: 24,
    pondType: 'Open Raceway',
    description: 'Precision alkalinity control pond with automated bicarbonate buffer dosing.',
    lastHarvest: '2026-09-07',
    dailyGrowthRate: 13.0,
    co2InjectionRate: 1.05,
    imageUrl: '/images/ponds/pond_pushkar.jpg',
  },
  {
    id: 'p-sam-3',
    name: 'Pond Banas',
    farmId: 'farm-3',
    farmName: 'Sambhar Salt Lake Bio-Culture Site',
    species: 'Chlorella pyrenoidosa',
    speciesCommon: 'Protein-Dense Strain',
    status: 'Healthy',
    biomass: 0.83,
    temperature: 29.0,
    ph: 8.1,
    dissolvedOxygen: 7.5,
    turbidity: 34,
    nitrogen: 8.2,
    volumeLiters: 105000,
    areaSqM: 2800,
    depthCm: 23,
    pondType: 'Raceway Basin',
    description: 'High-density growth basin feeding permanent biochar pyrolysis feedstock.',
    lastHarvest: '2026-08-29',
    dailyGrowthRate: 12.1,
    co2InjectionRate: 0.9,
    imageUrl: '/images/ponds/pond_banas.jpg',
  },

  // 4. Kochi Blue-Carbon Marine Facility (3 Ponds)
  {
    id: 'p-6',
    name: 'Pond Periyar',
    farmId: 'farm-4',
    farmName: 'Kochi Blue-Carbon Marine Facility',
    species: 'Nannochloropsis oculata',
    speciesCommon: 'Marine EPA Lipid Strain',
    status: 'Healthy',
    biomass: 1.15,
    temperature: 26.5,
    ph: 7.9,
    dissolvedOxygen: 8.0,
    turbidity: 28,
    nitrogen: 9.2,
    volumeLiters: 130000,
    areaSqM: 3200,
    depthCm: 24,
    pondType: 'Photobioreactor (PBR)',
    description: 'Advanced closed photobioreactor array engineered for high-purity cultivation and maximum photosynthetic efficiency.',
    lastHarvest: '2026-09-12',
    dailyGrowthRate: 12.8,
    co2InjectionRate: 1.3,
    imageUrl: '/images/ponds/pond_periyar.jpg',
  },
  {
    id: 'p-koc-2',
    name: 'Pond Pamba',
    farmId: 'farm-4',
    farmName: 'Kochi Blue-Carbon Marine Facility',
    species: 'Tetraselmis suecica',
    speciesCommon: 'Green Flagellate Algae',
    status: 'Healthy',
    biomass: 0.98,
    temperature: 26.8,
    ph: 8.0,
    dissolvedOxygen: 7.8,
    turbidity: 31,
    nitrogen: 8.9,
    volumeLiters: 115000,
    areaSqM: 2900,
    depthCm: 25,
    pondType: 'Precision Raceway',
    description: 'Estuarine-fed brackish basin with continuous paddle wheel circulation.',
    lastHarvest: '2026-09-05',
    dailyGrowthRate: 13.5,
    co2InjectionRate: 1.1,
    imageUrl: '/images/ponds/pond_pamba.jpg',
  },
  {
    id: 'p-koc-3',
    name: 'Pond Chalakudy',
    farmId: 'farm-4',
    farmName: 'Kochi Blue-Carbon Marine Facility',
    species: 'Isochrysis galbana',
    speciesCommon: 'Golden-Brown Microalgae',
    status: 'Healthy',
    biomass: 0.92,
    temperature: 26.2,
    ph: 7.8,
    dissolvedOxygen: 8.1,
    turbidity: 26,
    nitrogen: 9.4,
    volumeLiters: 90000,
    areaSqM: 2300,
    depthCm: 22,
    pondType: 'Closed PBR System',
    description: 'High-purity marine seed bioreactor with integrated LED supplemental spectrum.',
    lastHarvest: '2026-09-11',
    dailyGrowthRate: 11.9,
    co2InjectionRate: 1.25,
    imageUrl: '/images/ponds/pond_chalakudy.jpg',
  },

  // 5. Chilika Lagoon Bio-Sequestration Hub (3 Ponds)
  {
    id: 'p-chi-1',
    name: 'Pond Mahanadi',
    farmId: 'farm-5',
    farmName: 'Chilika Lagoon Bio-Sequestration Hub',
    species: 'Chlorella vulgaris',
    speciesCommon: 'Brackish Wetland Chlorella',
    status: 'Healthy',
    biomass: 0.89,
    temperature: 27.6,
    ph: 8.1,
    dissolvedOxygen: 7.7,
    turbidity: 33,
    nitrogen: 8.7,
    volumeLiters: 160000,
    areaSqM: 4000,
    depthCm: 26,
    pondType: 'Estuarine Raceway',
    description: 'Large-scale brackish water raceway operating under strict Ramsar ecological safeguards.',
    lastHarvest: '2026-09-08',
    dailyGrowthRate: 13.6,
    co2InjectionRate: 1.15,
    imageUrl: '/images/ponds/pond_mahanadi.jpg',
  },
  {
    id: 'p-chi-2',
    name: 'Pond Daya',
    farmId: 'farm-5',
    farmName: 'Chilika Lagoon Bio-Sequestration Hub',
    species: 'Scenedesmus obliquus',
    speciesCommon: 'Durable Bio-Polymer Strain',
    status: 'Healthy',
    biomass: 0.85,
    temperature: 27.9,
    ph: 8.2,
    dissolvedOxygen: 7.4,
    turbidity: 36,
    nitrogen: 8.3,
    volumeLiters: 110000,
    areaSqM: 2800,
    depthCm: 24,
    pondType: 'Open Raceway',
    description: 'Lagoon-adjacent bio-sequestration unit with gravity drainage harvesting.',
    lastHarvest: '2026-09-03',
    dailyGrowthRate: 12.3,
    co2InjectionRate: 0.95,
    imageUrl: '/images/ponds/pond_daya.jpg',
  },
  {
    id: 'p-chi-3',
    name: 'Pond Bhargavi',
    farmId: 'farm-5',
    farmName: 'Chilika Lagoon Bio-Sequestration Hub',
    species: 'Spirulina maxima',
    speciesCommon: 'High-Volume Blue-Green Strain',
    status: 'Healthy',
    biomass: 0.80,
    temperature: 28.1,
    ph: 8.4,
    dissolvedOxygen: 7.1,
    turbidity: 38,
    nitrogen: 8.0,
    volumeLiters: 95000,
    areaSqM: 2500,
    depthCm: 22,
    pondType: 'Open Raceway',
    description: 'High-efficiency carbon absorption basin optimized for monsoon corridor irradiance.',
    lastHarvest: '2026-08-31',
    dailyGrowthRate: 11.0,
    co2InjectionRate: 0.8,
    imageUrl: '/images/ponds/pond_bhargavi.jpg',
  },

  // 6. Bhavnagar Marine Algae Centre (3 Ponds)
  {
    id: 'p-3',
    name: 'Pond Shetrunji',
    farmId: 'farm-6',
    farmName: 'Bhavnagar Marine Algae Centre',
    species: 'Chlorella vulgaris',
    speciesCommon: 'Gulf Marine Chlorella',
    status: 'Healthy',
    biomass: 0.90,
    temperature: 28.3,
    ph: 8.1,
    dissolvedOxygen: 7.6,
    turbidity: 35,
    nitrogen: 8.8,
    volumeLiters: 140000,
    areaSqM: 3600,
    depthCm: 26,
    pondType: 'Open Raceway',
    description: 'Flagship commercial raceway utilizing filtered Gulf of Khambhat tidal seawater.',
    lastHarvest: '2026-09-11',
    dailyGrowthRate: 13.8,
    co2InjectionRate: 1.2,
    imageUrl: '/images/ponds/pond_shetrunji.jpg',
  },
  {
    id: 'p-bha-2',
    name: 'Pond Dhadhar',
    farmId: 'farm-6',
    farmName: 'Bhavnagar Marine Algae Centre',
    species: 'Spirulina platensis',
    speciesCommon: 'Industrial Bioplastic Feedstock',
    status: 'Healthy',
    biomass: 0.86,
    temperature: 28.6,
    ph: 8.3,
    dissolvedOxygen: 7.3,
    turbidity: 37,
    nitrogen: 8.5,
    volumeLiters: 105000,
    areaSqM: 2700,
    depthCm: 24,
    pondType: 'Open Raceway',
    description: 'Commercial cultivation raceway dedicated to industrial biopolymer production.',
    lastHarvest: '2026-09-06',
    dailyGrowthRate: 12.5,
    co2InjectionRate: 1.0,
    imageUrl: '/images/ponds/pond_dhadhar.jpg',
  },
  {
    id: 'p-bha-3',
    name: 'Pond Ghela',
    farmId: 'farm-6',
    farmName: 'Bhavnagar Marine Algae Centre',
    species: 'Dunaliella salina',
    speciesCommon: 'Marine Halotolerant Strain',
    status: 'Healthy',
    biomass: 0.78,
    temperature: 29.1,
    ph: 8.5,
    dissolvedOxygen: 7.0,
    turbidity: 32,
    nitrogen: 7.7,
    volumeLiters: 80000,
    areaSqM: 2100,
    depthCm: 20,
    pondType: 'High-Salinity Raceway',
    description: 'High-salinity basin engineered for resilient carbon locking under high ambient warmth.',
    lastHarvest: '2026-08-27',
    dailyGrowthRate: 10.8,
    co2InjectionRate: 0.75,
    imageUrl: '/images/ponds/pond_ghela.jpg',
  }
];

export interface FarmDetails {
  id: string;
  name: string;
  location: string;
  coordinates: { lat: number; lng: number };
  totalAreaSqM: number;
  elevation: string;
  climate: string;
  waterSource: string;
  operationalSince: string;
  certifications: string[];
  description: string;
  manager: string;
  annualCapacity: string;
  energySource: string;
  pondCount: number;
  imageUrl: string;
}

export const DEMO_FARMS: FarmDetails[] = [
  {
    id: 'farm-1',
    name: 'Kutch Bio-Raceway Facility',
    location: 'Kutch, Gujarat, India',
    coordinates: { lat: 23.733, lng: 69.859 },
    totalAreaSqM: 18500,
    elevation: '12 m AMSL',
    climate: 'Arid Coastal Basin — 345+ sunny days/year',
    waterSource: 'Gulf of Kutch seawater & brackish aquifers (recycled)',
    operationalSince: '2024-01-10',
    certifications: ['ISO 14001', 'Verra Carbon Standard', 'ISCC PLUS'],
    description: 'Flagship hypersaline and open raceway carbon sequestration hub leveraging Gujarat\'s high solar irradiance corridor for year-round microalgae biomass production.',
    manager: 'Dharmesh V.',
    annualCapacity: '240 tonnes dry biomass',
    energySource: '100% On-site Solar PV (3.2 MW)',
    pondCount: 4,
    imageUrl: '/images/farms/kutch.jpg',
  },
  {
    id: 'farm-2',
    name: 'Rameswaram Coastal Algae Hub',
    location: 'Rameswaram, Tamil Nadu, India',
    coordinates: { lat: 9.287, lng: 79.312 },
    totalAreaSqM: 14200,
    elevation: '5 m AMSL',
    climate: 'Tropical Marine — Year-round warm coastal ambient',
    waterSource: 'Palk Strait Marine Intake',
    operationalSince: '2024-05-18',
    certifications: ['Blue Carbon Protocol', 'ISO 14064-2'],
    description: 'Coastal macro and microalgae carbon sequestration pilot facility capturing atmospheric CO₂ into durable biopolymer feedstocks.',
    manager: 'Dr. Anand Ramanathan',
    annualCapacity: '190 tonnes dry biomass',
    energySource: 'Coastal Wind & Hybrid Solar (2.8 MW)',
    pondCount: 3,
    imageUrl: '/images/farms/rameswaram.jpg',
  },
  {
    id: 'farm-3',
    name: 'Sambhar Salt Lake Bio-Culture Site',
    location: 'Sambhar Lake, Rajasthan, India',
    coordinates: { lat: 26.901, lng: 75.006 },
    totalAreaSqM: 22000,
    elevation: '360 m AMSL',
    climate: 'Semi-Arid Salt Playa — Extreme solar radiation',
    waterSource: 'Natural Inland Hyper-Saline Brine Basin',
    operationalSince: '2024-08-01',
    certifications: ['Gold Standard CER', 'ISO 9001'],
    description: 'Natural inland saline basin optimized for halophilic microalgae cultivation, maximizing permanent biochar and mineralized carbon credits.',
    manager: 'Vikramaditya Singh',
    annualCapacity: '310 tonnes dry biomass',
    energySource: 'Rooftop & Floating Solar PV (4.0 MW)',
    pondCount: 3,
    imageUrl: '/images/farms/sambhar.jpg',
  },
  {
    id: 'farm-4',
    name: 'Kochi Blue-Carbon Marine Facility',
    location: 'Kochi, Kerala, India',
    coordinates: { lat: 9.931, lng: 76.267 },
    totalAreaSqM: 11800,
    elevation: '3 m AMSL',
    climate: 'Tropical Coastal Monsoon Corridor',
    waterSource: 'Vembanad Estuary & Arabian Sea Mixed Feed',
    operationalSince: '2024-11-20',
    certifications: ['Marine Stewardship MRV', 'ISO 14001'],
    description: 'Estuarine closed photobioreactor and raceway hub integrated with coastal aquaculture for net-negative carbon removal.',
    manager: 'Meera Nair',
    annualCapacity: '160 tonnes dry biomass',
    energySource: 'Hydro-Solar Microgrid (1.8 MW)',
    pondCount: 3,
    imageUrl: '/images/farms/kochi.jpg',
  },
  {
    id: 'farm-5',
    name: 'Chilika Lagoon Bio-Sequestration Hub',
    location: 'Chilika, Odisha, India',
    coordinates: { lat: 19.716, lng: 85.321 },
    totalAreaSqM: 16500,
    elevation: '2 m AMSL',
    climate: 'Coastal Brackish Wetland',
    waterSource: 'Chilika Brackish Water Inflow',
    operationalSince: '2025-02-14',
    certifications: ['Ramsar Wetland MRV Guidelines', 'Verra VCS'],
    description: 'Brackish water microalgae bio-sequestration research and commercial MRV carbon sink operating under strict ecological safeguards.',
    manager: 'Subhashree Patnaik',
    annualCapacity: '210 tonnes dry biomass',
    energySource: 'On-site Solar + Grid Backing (2.5 MW)',
    pondCount: 3,
    imageUrl: '/images/farms/chilika.jpg',
  },
  {
    id: 'farm-6',
    name: 'Bhavnagar Marine Algae Centre',
    location: 'Bhavnagar, Gujarat, India',
    coordinates: { lat: 21.764, lng: 72.151 },
    totalAreaSqM: 13900,
    elevation: '11 m AMSL',
    climate: 'Gulf of Khambhat Semi-Arid Marine',
    waterSource: 'Gulf Marine Tidal Channel (Filtered)',
    operationalSince: '2025-04-05',
    certifications: ['ISO 14064-2', 'ISCC PLUS'],
    description: 'Commercial Chlorella and Spirulina biomass production facility for industrial bioplastic feedstocks and durable carbon locking.',
    manager: 'Ketan Patel',
    annualCapacity: '175 tonnes dry biomass',
    energySource: 'Wind-Solar Hybrid (2.2 MW)',
    pondCount: 3,
    imageUrl: '/images/farms/bhavnagar.jpg',
  }
];

export const DEMO_FARM = DEMO_FARMS[0];
