from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
import uuid
from typing import List

from .. import models, schemas
from ..database import get_db
from ..evidence.service import generate_evidence_package

router = APIRouter()

@router.post("/ponds/{pond_id}/evidence-packages", response_model=schemas.EvidencePackageResponse, status_code=201)
def create_evidence_package(
    pond_id: uuid.UUID,
    package_in: schemas.EvidencePackageCreate,
    db: Session = Depends(get_db)
):
    pond = db.query(models.Pond).filter(models.Pond.id == pond_id).first()
    if not pond:
        raise HTTPException(status_code=404, detail="Pond not found")
        
    pkg = generate_evidence_package(
        db,
        farm_id=pond.farm_id,
        pond_id=pond.id,
        start_date=package_in.reporting_period_start,
        end_date=package_in.reporting_period_end
    )
    return pkg

@router.get("/ponds/{pond_id}/evidence-packages", response_model=List[schemas.EvidencePackageResponse])
def list_evidence_packages(
    pond_id: uuid.UUID,
    db: Session = Depends(get_db)
):
    packages = db.query(models.EvidencePackage).filter(models.EvidencePackage.pond_id == pond_id).order_by(models.EvidencePackage.created_at.desc()).all()
    return packages

@router.get("/evidence-packages/{pkg_id}", response_model=schemas.EvidencePackageResponse)
def get_evidence_package(
    pkg_id: uuid.UUID,
    db: Session = Depends(get_db)
):
    pkg = db.query(models.EvidencePackage).filter(models.EvidencePackage.id == pkg_id).first()
    if not pkg:
        raise HTTPException(status_code=404, detail="Evidence Package not found")
    return pkg

@router.get("/evidence-packages/{pkg_id}/report")
def get_evidence_package_report(
    pkg_id: uuid.UUID,
    db: Session = Depends(get_db)
):
    pkg = db.query(models.EvidencePackage).filter(models.EvidencePackage.id == pkg_id).first()
    if not pkg:
        raise HTTPException(status_code=404, detail="Evidence Package not found")
        
    farm = db.query(models.Farm).filter(models.Farm.id == pkg.farm_id).first()
    pond = db.query(models.Pond).filter(models.Pond.id == pkg.pond_id).first()
    
    html = f"""
    <html>
    <head>
        <title>Verification-Ready Report: {pond.name}</title>
        <style>
            body {{ font-family: sans-serif; padding: 20px; }}
            .header {{ border-bottom: 2px solid #ccc; padding-bottom: 10px; margin-bottom: 20px; }}
            .section {{ margin-bottom: 30px; }}
            .simulated-warning {{ background-color: #fff3cd; color: #856404; padding: 10px; border: 1px solid #ffeeba; border-radius: 4px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Verification-Ready Evidence Report</h1>
            <p><strong>Farm:</strong> {farm.name}</p>
            <p><strong>Pond:</strong> {pond.name}</p>
            <p><strong>Reporting Period:</strong> {pkg.reporting_period_start.strftime('%Y-%m-%d')} to {pkg.reporting_period_end.strftime('%Y-%m-%d')}</p>
            <p><strong>Package Hash:</strong> <code>{pkg.canonical_hash}</code></p>
        </div>
    """
    
    if pkg.contains_simulated_data:
        html += """
        <div class="simulated-warning">
            <strong>Data source: SIMULATED</strong><br/>
            Demonstration data generated by the AlgaX simulation engine.
        </div>
        """
        
    html += f"""
        <div class="section">
            <h2>Completeness</h2>
            <p>Status: <strong>{pkg.completeness.value}</strong></p>
            <p>Limitations: {len(pkg.limitations_json)} noted</p>
        </div>
        
        <div class="section">
            <h2>Modeled Estimate (Carbon)</h2>
            <p>Total Model Runs: {len(pkg.model_evidence_json)}</p>
            <p>Total Carbon Estimates: {len(pkg.carbon_evidence_json)}</p>
        </div>
        
        <div class="section">
            <h2>Visual Observations (Imagery)</h2>
            <p>Total Images Processed: {len(pkg.imagery_evidence_json)}</p>
        </div>
        
        <div class="section">
            <h2>Cross-Validation (Alignment)</h2>
            <p>Total Runs: {len(pkg.cross_validation_evidence_json)}</p>
        </div>
    </body>
    </html>
    """
    from fastapi.responses import HTMLResponse
    return HTMLResponse(content=html)


@router.get("/evidence-packages/{pkg_id}/review/actions", response_model=List[schemas.ReviewActionResponse])
def get_review_actions(
    pkg_id: uuid.UUID,
    db: Session = Depends(get_db)
):
    pkg = db.query(models.EvidencePackage).filter(models.EvidencePackage.id == pkg_id).first()
    if not pkg:
        raise HTTPException(status_code=404, detail="Evidence Package not found")
        
    actions = db.query(models.ReviewAction).filter(models.ReviewAction.package_id == pkg_id).order_by(models.ReviewAction.created_at.asc()).all()
    return actions

@router.post("/evidence-packages/{pkg_id}/review/actions", response_model=schemas.ReviewActionResponse, status_code=201)
def create_review_action(
    pkg_id: uuid.UUID,
    action_in: schemas.ReviewActionCreate,
    db: Session = Depends(get_db)
):
    pkg = db.query(models.EvidencePackage).filter(models.EvidencePackage.id == pkg_id).first()
    if not pkg:
        raise HTTPException(status_code=404, detail="Evidence Package not found")
        
    # Create the action
    new_action = models.ReviewAction(
        package_id=pkg.id,
        actor="reviewer@algax.com", # Mocking the actor since we don't have auth context in this snippet yet
        action=models.ReviewActionType(action_in.action),
        note=action_in.note
    )
    db.add(new_action)
    
    # Mutate package state based on action
    if new_action.action == models.ReviewActionType.START_REVIEW:
        pkg.review_state = models.ReviewState.IN_REVIEW
    elif new_action.action == models.ReviewActionType.FLAG_FOR_ATTENTION:
        pkg.review_state = models.ReviewState.NEEDS_ATTENTION
    elif new_action.action == models.ReviewActionType.REQUEST_MORE_EVIDENCE:
        pkg.review_state = models.ReviewState.NEEDS_ATTENTION
    elif new_action.action == models.ReviewActionType.MARK_REVIEWED:
        if pkg.review_state != models.ReviewState.NEEDS_ATTENTION: # Simplified logic
            pkg.review_state = models.ReviewState.READY_FOR_EXTERNAL_REVIEW
    elif new_action.action == models.ReviewActionType.CLOSE_REVIEW:
        pkg.review_state = models.ReviewState.CLOSED
        
    db.commit()
    db.refresh(new_action)
    return new_action
