'use client';

import React, { useState } from 'react';
import { Play, Square, FastForward, RotateCcw } from 'lucide-react';

export default function SimulationControlPage() {
  const [activeScenario, setActiveScenario] = useState('Healthy Pond');
  const [status, setStatus] = useState('Running');
  
  const handleRun = (scenario: string) => {
    setActiveScenario(scenario);
    setStatus('Running');
  };

  const handleStop = () => {
    setStatus('Stopped');
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-12">
      <div>
        <h1 className="text-3xl font-bold text-gray-900 tracking-tight">Simulation Control</h1>
        <p className="text-gray-500 mt-1">Data generated by AlgaeMRV&apos;s farm simulator for demonstration.</p>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center justify-between border-b border-gray-100 pb-4 mb-6">
          <div>
            <h2 className="text-lg font-bold text-gray-900">Genesis Algae Farm</h2>
            <div className="flex items-center gap-2 mt-1">
              <span className="text-sm text-gray-500">Status:</span>
              <span className={`text-xs font-bold px-2 py-0.5 rounded-full uppercase ${
                status === 'Running' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'
              }`}>{status}</span>
            </div>
          </div>
          <div className="text-right">
            <div className="text-sm text-gray-500">Current Simulated Time</div>
            <div className="text-xl font-mono text-gray-900 font-bold">Sep 12, 10:24 AM</div>
          </div>
        </div>

        <div className="mb-8">
          <h3 className="text-sm font-bold text-gray-900 mb-3 uppercase tracking-wider">Playback Controls</h3>
          <div className="flex items-center gap-3">
            <button className="flex items-center gap-2 bg-gray-100 hover:bg-gray-200 text-gray-800 px-4 py-2 rounded-lg font-medium transition-colors">
              <FastForward className="w-4 h-4" /> 1×
            </button>
            <button className="flex items-center gap-2 bg-gray-100 hover:bg-gray-200 text-gray-800 px-4 py-2 rounded-lg font-medium transition-colors">
              <FastForward className="w-4 h-4" /> 5×
            </button>
            <button className="flex items-center gap-2 bg-gray-100 hover:bg-gray-200 text-gray-800 px-4 py-2 rounded-lg font-medium transition-colors">
              <FastForward className="w-4 h-4" /> 10×
            </button>
            
            <div className="h-8 w-px bg-gray-300 mx-2"></div>
            
            <button onClick={handleStop} className="flex items-center gap-2 bg-red-50 hover:bg-red-100 text-red-700 px-4 py-2 rounded-lg font-medium transition-colors">
              <Square className="w-4 h-4 text-red-500" /> Stop
            </button>
            <button className="flex items-center gap-2 bg-gray-50 hover:bg-gray-100 text-gray-700 px-4 py-2 rounded-lg font-medium border border-gray-200 transition-colors">
              <RotateCcw className="w-4 h-4" /> Reset
            </button>
          </div>
        </div>

        <div>
          <h3 className="text-sm font-bold text-gray-900 mb-3 uppercase tracking-wider">Scenarios</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <ScenarioCard 
              title="Healthy Pond" 
              description="Normal biological behavior." 
              isActive={activeScenario === 'Healthy Pond'}
              onRun={() => handleRun('Healthy Pond')}
            />
            <ScenarioCard 
              title="Nutrient Depletion" 
              description="Expected: Nitrogen decreases → growth slows → limitation increases → anomaly appears." 
              isActive={activeScenario === 'Nutrient Depletion'}
              onRun={() => handleRun('Nutrient Depletion')}
            />
            <ScenarioCard 
              title="Heatwave" 
              description="Expected: Temperature stress increases → growth slows → anomaly appears." 
              isActive={activeScenario === 'Heatwave'}
              onRun={() => handleRun('Heatwave')}
            />
            <ScenarioCard 
              title="Sensor Dropout" 
              description="Expected: Sensor readings stop → sensor anomaly appears." 
              isActive={activeScenario === 'Sensor Dropout'}
              onRun={() => handleRun('Sensor Dropout')}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

function ScenarioCard({ title, description, isActive, onRun }: { title: string, description: string, isActive: boolean, onRun: () => void }) {
  return (
    <div className={`border rounded-lg p-4 transition-colors ${isActive ? 'border-green-500 bg-green-50' : 'border-gray-200 bg-white hover:border-gray-300'}`}>
      <div className="flex items-start justify-between mb-2">
        <h4 className="font-bold text-gray-900">{title}</h4>
        {isActive && <span className="flex h-2.5 w-2.5 rounded-full bg-green-500"></span>}
      </div>
      <p className="text-xs text-gray-600 mb-4 h-12">{description}</p>
      <button 
        onClick={onRun}
        className={`w-full py-2 rounded font-medium text-sm flex items-center justify-center gap-2 ${
          isActive ? 'bg-green-600 text-white hover:bg-green-700' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
        }`}
      >
        <Play className="w-4 h-4" /> {isActive ? 'Running' : 'Run Scenario'}
      </button>
    </div>
  );
}
